// Code generated by moshi-kotlin-codegen. Do not edit.
package com.weather.android.kdal.model

import com.squareup.moshi.*
import java.lang.NullPointerException
import kotlin.Int
import kotlin.String

class V3WxIndicesPollenHistoricalJsonAdapter(moshi: Moshi) : JsonAdapter<V3WxIndicesPollenHistorical>() {
    private val options: JsonReader.Options =
            JsonReader.Options.of("reportTimeLocal", "treePollenIndex", "treePollenDescription", "grassPollenIndex", "grassPollenDescription", "ragweedPollenIndex", "ragweedPollenDescription")

    private val listOfStringAdapter: JsonAdapter<List<String>> =
            moshi.adapter<List<String>>(Types.newParameterizedType(List::class.java, String::class.java)).nonNull()

    private val listOfNullableIntAdapter: JsonAdapter<List<Int?>> =
            moshi.adapter<List<Int?>>(Types.newParameterizedType(List::class.java, Int::class.java)).nonNull()

    private val listOfNullableStringAdapter: JsonAdapter<List<String?>> =
            moshi.adapter<List<String?>>(Types.newParameterizedType(List::class.java, String::class.java)).nonNull()

    override fun toString(): String = "GeneratedJsonAdapter(V3WxIndicesPollenHistorical)"

    override fun fromJson(reader: JsonReader): V3WxIndicesPollenHistorical {
        var reportTimeLocal: List<String>? = null
        var treePollenIndex: List<Int?>? = null
        var treePollenDescription: List<String?>? = null
        var grassPollenIndex: List<Int?>? = null
        var grassPollenDescription: List<String?>? = null
        var ragweedPollenIndex: List<Int?>? = null
        var ragweedPollenDescription: List<String?>? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> reportTimeLocal = listOfStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'reportTimeLocal' was null at ${reader.path}")
                1 -> treePollenIndex = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'treePollenIndex' was null at ${reader.path}")
                2 -> treePollenDescription = listOfNullableStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'treePollenDescription' was null at ${reader.path}")
                3 -> grassPollenIndex = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'grassPollenIndex' was null at ${reader.path}")
                4 -> grassPollenDescription = listOfNullableStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'grassPollenDescription' was null at ${reader.path}")
                5 -> ragweedPollenIndex = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'ragweedPollenIndex' was null at ${reader.path}")
                6 -> ragweedPollenDescription = listOfNullableStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'ragweedPollenDescription' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = V3WxIndicesPollenHistorical(
                reportTimeLocal = reportTimeLocal ?: throw JsonDataException("Required property 'reportTimeLocal' missing at ${reader.path}"),
                treePollenIndex = treePollenIndex ?: throw JsonDataException("Required property 'treePollenIndex' missing at ${reader.path}"),
                treePollenDescription = treePollenDescription ?: throw JsonDataException("Required property 'treePollenDescription' missing at ${reader.path}"),
                grassPollenIndex = grassPollenIndex ?: throw JsonDataException("Required property 'grassPollenIndex' missing at ${reader.path}"),
                grassPollenDescription = grassPollenDescription ?: throw JsonDataException("Required property 'grassPollenDescription' missing at ${reader.path}"),
                ragweedPollenIndex = ragweedPollenIndex ?: throw JsonDataException("Required property 'ragweedPollenIndex' missing at ${reader.path}"),
                ragweedPollenDescription = ragweedPollenDescription ?: throw JsonDataException("Required property 'ragweedPollenDescription' missing at ${reader.path}"))
        return result
    }

    override fun toJson(writer: JsonWriter, value: V3WxIndicesPollenHistorical?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("reportTimeLocal")
        listOfStringAdapter.toJson(writer, value.reportTimeLocal)
        writer.name("treePollenIndex")
        listOfNullableIntAdapter.toJson(writer, value.treePollenIndex)
        writer.name("treePollenDescription")
        listOfNullableStringAdapter.toJson(writer, value.treePollenDescription)
        writer.name("grassPollenIndex")
        listOfNullableIntAdapter.toJson(writer, value.grassPollenIndex)
        writer.name("grassPollenDescription")
        listOfNullableStringAdapter.toJson(writer, value.grassPollenDescription)
        writer.name("ragweedPollenIndex")
        listOfNullableIntAdapter.toJson(writer, value.ragweedPollenIndex)
        writer.name("ragweedPollenDescription")
        listOfNullableStringAdapter.toJson(writer, value.ragweedPollenDescription)
        writer.endObject()
    }
}
