// Code generated by moshi-kotlin-codegen. Do not edit.
package com.weather.android.kdal.model

import com.squareup.moshi.*
import java.lang.NullPointerException
import kotlin.Double
import kotlin.Int
import kotlin.String

class V3WxConditionsHistoricalDailysummaryJsonAdapter(moshi: Moshi) : JsonAdapter<V3WxConditionsHistoricalDailysummary>() {
    private val options: JsonReader.Options =
            JsonReader.Options.of("dayOfWeek", "iconCodeDay", "iconCodeNight", "precip24Hour", "rain24Hour", "snow24Hour", "temperatureMax", "temperatureMin", "validTimeLocal", "validTimeUtc", "wxPhraseLongDay", "wxPhraseLongNight")

    private val listOfStringAdapter: JsonAdapter<List<String>> =
            moshi.adapter<List<String>>(Types.newParameterizedType(List::class.java, String::class.java)).nonNull()

    private val listOfNullableIntAdapter: JsonAdapter<List<Int?>> =
            moshi.adapter<List<Int?>>(Types.newParameterizedType(List::class.java, Int::class.java)).nonNull()

    private val listOfNullableDoubleAdapter: JsonAdapter<List<Double?>> =
            moshi.adapter<List<Double?>>(Types.newParameterizedType(List::class.java, Double::class.java)).nonNull()

    private val listOfLongAdapter: JsonAdapter<List<Long>> =
            moshi.adapter<List<Long>>(Types.newParameterizedType(List::class.java, java.lang.Long::class.java)).nonNull()

    private val listOfNullableStringAdapter: JsonAdapter<List<String?>> =
            moshi.adapter<List<String?>>(Types.newParameterizedType(List::class.java, String::class.java)).nonNull()

    override fun toString(): String = "GeneratedJsonAdapter(V3WxConditionsHistoricalDailysummary)"

    override fun fromJson(reader: JsonReader): V3WxConditionsHistoricalDailysummary {
        var dayOfWeek: List<String>? = null
        var iconCodeDay: List<Int?>? = null
        var iconCodeNight: List<Int?>? = null
        var precip24Hour: List<Double?>? = null
        var rain24Hour: List<Double?>? = null
        var snow24Hour: List<Double?>? = null
        var temperatureMax: List<Int?>? = null
        var temperatureMin: List<Int?>? = null
        var validTimeLocal: List<String>? = null
        var validTimeUtc: List<Long>? = null
        var wxPhraseLongDay: List<String?>? = null
        var wxPhraseLongNight: List<String?>? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> dayOfWeek = listOfStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'dayOfWeek' was null at ${reader.path}")
                1 -> iconCodeDay = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'iconCodeDay' was null at ${reader.path}")
                2 -> iconCodeNight = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'iconCodeNight' was null at ${reader.path}")
                3 -> precip24Hour = listOfNullableDoubleAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'precip24Hour' was null at ${reader.path}")
                4 -> rain24Hour = listOfNullableDoubleAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'rain24Hour' was null at ${reader.path}")
                5 -> snow24Hour = listOfNullableDoubleAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'snow24Hour' was null at ${reader.path}")
                6 -> temperatureMax = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'temperatureMax' was null at ${reader.path}")
                7 -> temperatureMin = listOfNullableIntAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'temperatureMin' was null at ${reader.path}")
                8 -> validTimeLocal = listOfStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'validTimeLocal' was null at ${reader.path}")
                9 -> validTimeUtc = listOfLongAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'validTimeUtc' was null at ${reader.path}")
                10 -> wxPhraseLongDay = listOfNullableStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'wxPhraseLongDay' was null at ${reader.path}")
                11 -> wxPhraseLongNight = listOfNullableStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'wxPhraseLongNight' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = V3WxConditionsHistoricalDailysummary(
                dayOfWeek = dayOfWeek ?: throw JsonDataException("Required property 'dayOfWeek' missing at ${reader.path}"),
                iconCodeDay = iconCodeDay ?: throw JsonDataException("Required property 'iconCodeDay' missing at ${reader.path}"),
                iconCodeNight = iconCodeNight ?: throw JsonDataException("Required property 'iconCodeNight' missing at ${reader.path}"),
                precip24Hour = precip24Hour ?: throw JsonDataException("Required property 'precip24Hour' missing at ${reader.path}"),
                rain24Hour = rain24Hour ?: throw JsonDataException("Required property 'rain24Hour' missing at ${reader.path}"),
                snow24Hour = snow24Hour ?: throw JsonDataException("Required property 'snow24Hour' missing at ${reader.path}"),
                temperatureMax = temperatureMax ?: throw JsonDataException("Required property 'temperatureMax' missing at ${reader.path}"),
                temperatureMin = temperatureMin ?: throw JsonDataException("Required property 'temperatureMin' missing at ${reader.path}"),
                validTimeLocal = validTimeLocal ?: throw JsonDataException("Required property 'validTimeLocal' missing at ${reader.path}"),
                validTimeUtc = validTimeUtc ?: throw JsonDataException("Required property 'validTimeUtc' missing at ${reader.path}"),
                wxPhraseLongDay = wxPhraseLongDay ?: throw JsonDataException("Required property 'wxPhraseLongDay' missing at ${reader.path}"),
                wxPhraseLongNight = wxPhraseLongNight ?: throw JsonDataException("Required property 'wxPhraseLongNight' missing at ${reader.path}"))
        return result
    }

    override fun toJson(writer: JsonWriter, value: V3WxConditionsHistoricalDailysummary?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("dayOfWeek")
        listOfStringAdapter.toJson(writer, value.dayOfWeek)
        writer.name("iconCodeDay")
        listOfNullableIntAdapter.toJson(writer, value.iconCodeDay)
        writer.name("iconCodeNight")
        listOfNullableIntAdapter.toJson(writer, value.iconCodeNight)
        writer.name("precip24Hour")
        listOfNullableDoubleAdapter.toJson(writer, value.precip24Hour)
        writer.name("rain24Hour")
        listOfNullableDoubleAdapter.toJson(writer, value.rain24Hour)
        writer.name("snow24Hour")
        listOfNullableDoubleAdapter.toJson(writer, value.snow24Hour)
        writer.name("temperatureMax")
        listOfNullableIntAdapter.toJson(writer, value.temperatureMax)
        writer.name("temperatureMin")
        listOfNullableIntAdapter.toJson(writer, value.temperatureMin)
        writer.name("validTimeLocal")
        listOfStringAdapter.toJson(writer, value.validTimeLocal)
        writer.name("validTimeUtc")
        listOfLongAdapter.toJson(writer, value.validTimeUtc)
        writer.name("wxPhraseLongDay")
        listOfNullableStringAdapter.toJson(writer, value.wxPhraseLongDay)
        writer.name("wxPhraseLongNight")
        listOfNullableStringAdapter.toJson(writer, value.wxPhraseLongNight)
        writer.endObject()
    }
}
